SET IDENTITY_INSERT [dbo].[Sport] ON
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (11, N'MG4O8r8D6VpQtq', N'Велосипед Foxx Aztec 29', CAST(16540.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (12, N'nXiGQVB4XDHK8l', N'Велосипед Altair MTB HT 27.5 2.0 Disc (2021)', CAST(17990.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (13, N'cSZn9z5Vj2iokQ', N'Велосипед Foxx Aztec D 29 (2021)', CAST(18060.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (14, N'5IDhCsVvHP5QxH', N'Велосипед Skif 26 Disc (2021)', CAST(18290.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (15, N'FlL9OP5Ul4guNS', N'Велосипед Foxx Aztec D 27.5 (2021)', CAST(18300.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (16, N'90O9b9JJzCtZBf', N'Велосипед Black One Onix 26 (2021)', CAST(18490.0000 AS Money), 1)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (17, N'6AvLEeTYHaw5KN', N'Велосипед Skif 29 Disc (2021)', CAST(18890.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (18, N'ZxjwGmzqZQ7na4', N'Велосипед Altair MTB HT 29 2.0 Disc (2021)', CAST(18990.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (19, N'I4TIIC7KeWIQ9S', N'Велосипед Foxx Atlantic 26 (2021)', CAST(19470.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (20, N'HcCg3L2FnUMFIo', N'Велосипед Black One Element 26 D (2021)', CAST(19550.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (21, N'Fb4ZdQLhrVS9cw', N'Перчатки велосипедные Cyclotech PILOT', CAST(399.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (22, N'dCgFz14XFJnEVH', N'Шлем велосипедный Stern', CAST(1799.0000 AS Money), 3)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (23, N'55y78YnsmnyOTY', N'Набор защиты REACTION для велосипедиста', CAST(1199.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (24, N'G3vLoAc8TDjWud', N'Шлем велосипедный Stern цвет черный, зеленый', CAST(1799.0000 AS Money), 12)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (25, N'4mtrdnn2vM6Cwd', N'Велошорты Dainese цвет черный размер 44-46', CAST(10790.0000 AS Money), 10)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (26, N'iqchNwcPYsGlPZ', N'Джерси Dainese Otzarreta цвет серый, оранжевый размер 46-50', CAST(7199.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (27, N'MEx6HSpraLgLbi', N'Джерси мужское Dainese цвнт черный, белый, голубой размер 46-50', CAST(3779.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (28, N'1Y1K0DqJq1qLjo', N'Футболка мужская Dainese цвет черный размер 44-50', CAST(2799.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (29, N'umY1xJJHVAl8oc', N'Защита колен Dainese TRAIL SKINS PRO цвет черный', CAST(8799.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (30, N'lCAeKgzkCNXVtJ', N'Шлем велосипедный Uvex quatro цвет зеленый', CAST(10999.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (31, N'tIgkoTe7olP2to', N'Направляющая для тормоза V-brake для велосипеда', CAST(44.0000 AS Money), 24)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (32, N'lhytxsbsWAIQdw', N'Болт оси каретки под торцевой ключ, М8х16мм велосипедный', CAST(28.0000 AS Money), 39)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (33, N'B1Obc3wuQSuUq7', N'Втулка передняя 36 отв., FAT BIKE, алюминий, под диск 6 болтов, ось 3/8''''х135x175 мм, промподшипники для велосипеда', CAST(1465.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (34, N'0wJ9L2RnYCirkO', N'Съёмник каретки STG YC-26BB для Shimano для велосипеда', CAST(540.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (35, N'ikFPhA1lAJ33Sk', N'Тросик тормоза 1,5x2050 мм, FX-BC-012, головка 7х6мм для велосипеда', CAST(43.0000 AS Money), 26)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (36, N'FOIAzi39E9KAmB', N'Камера 10" × 2,0" NTG, бутил, автониппель', CAST(144.0000 AS Money), 12)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (37, N'RkSjrsQrb58sRf', N'Смазка для велосипедных цепей Dream bike, 120 мл', CAST(91.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (38, N'5x1Ygv6muZSedP', N'Грипсы 120 мм TY-NO-9097', CAST(161.0000 AS Money), 12)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (39, N'11DuDWDOOBCxAz', N'Цепь 5,6,7 скоростей HC-PJ-148A, 1/2x3/32x116L, 116 звеньев', CAST(280.0000 AS Money), 17)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (40, N'Md5NpUUm1CbIkk', N'Седло A06 260*240 мм', CAST(59.0000 AS Money), 20)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (41, N'ijoYID14BY7cIT', N'Коврик для фитнеса Demix цвет фиолетовый', CAST(299.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (42, N'W7M9auIdwCDQGk', N'Коврик для фитнеса Demix цвет серый ', CAST(299.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (43, N'O9zvPJY82MbqYy', N'Коврик для йоги Demix цвет синий ', CAST(999.0000 AS Money), 15)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (44, N'coHYorxzHQxHAK', N'Коврик для фитнеса Kettler цвет синий', CAST(1999.0000 AS Money), 10)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (45, N'3NoaN4ZXnRW1rN', N'Коврик для йоги Demix цвет синий, желтый', CAST(2449.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (46, N'3G2o4PhtMNEHhB', N'Мат для йоги Kettler цвет черный, розовый', CAST(2999.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (47, N'8eCxHKDrsk89RL', N'Коврик для йоги Kettler цвет серый, желтый с принтом', CAST(1599.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (48, N'pz5ZfmXv3Wx12k', N'Коврик для фитнеса SKLZ цвет серый', CAST(3999.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (49, N'nmutiSW28q9gNX', N'Мат для тренажеров Torneo цвет черный, зеленый', CAST(1799.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (50, N'sLs9i7AaAtMyGa', N'Коврик для тренажеров Torneo цвет серый', CAST(2999.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (51, N'6d7VQ7n7a4df9Y', N'Набор мини лент Set of mini-tapes', CAST(599.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (52, N'Ld7nAiP8418PDv', N'Лента силовая Demix цвет розовый', CAST(799.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (53, N'CtzESKqm0fbBhV', N'Крепление на дверь Demix', CAST(199.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (54, N'eimP3oqNiBqdOd', N'Манжеты для ног Demix', CAST(699.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (55, N'tTd24k327B8LdM', N'Эспандер-лента SKLZ Bands Light', CAST(1999.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (56, N'YAS0fdwsX4ZPZo', N'Ремень для пауэрлифтинга с пряжкой Demix, (2 иглы)', CAST(1999.0000 AS Money), 25)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (57, N'AYynDAJdfkqMba', N'Петли для функционального тренинга Demix', CAST(2999.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (58, N'qIJMyJhIY5GeAu', N'Полотенце для йоги', CAST(1499.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (59, N'2z2aiVIfFd2KZP
', N'Лента эластичная Elastic Band цвет желтый', CAST(499.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (60, N'oc7tTc2y1G7COj', N'Мяч массажный Torneo цвет зеленый', CAST(99.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (61, N'vxpZycvlmpq25h', N'Трос силовой Demix', CAST(199.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (62, N'Pjh21vfy5c4fa2
', N'Ручки для силовых тросов Demix', CAST(599.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (63, N'wAkNPLvGjLuWMk', N'Медицинбол Demix, 1 кг', CAST(999.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (64, N'3cW5fbV3XdqRfR', N'Ручка для одного силового троса SKLZ', CAST(1199.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (65, N'ErEAqQWmLnTpeN', N'Медицинбол Demix, 3 кг', CAST(1299.0000 AS Money), 3)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (66, N'YD2KjOKNgPTAlA', N'Крюки для турника и тяги Grozz', CAST(1299.0000 AS Money), 9)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (67, N'R9EYSweqeYqaUj', N'Трос силовой с легким сопротивлением SKLZ', CAST(1599.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (68, N'5kHfNKovmjL2K6', N'Медицинбол Demix, 7 кг', CAST(1799.0000 AS Money), 21)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (69, N'Wc6vnd6YsF7JnI', N'Петли для функционального тренинга Demix', CAST(1999.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (70, N'X38hWHzR1OcBDY', N'Тренировочный парашют для бега SKLZ', CAST(2999.0000 AS Money), 1)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (71, N'O5A6qflpbdEYFJ', N'Скакалка скоростная Torneo', CAST(199.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (72, N'eEZ6jqs6miEoMB', N'Палки для беговых лыж Nordway Active', CAST(549.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (73, N'7egvNuGfHluRVo', N'Липучки для беговых лыж Nordway цвет черный', CAST(149.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (74, N'a28INVusZxrLwc', N'Ботинки для беговых лыж Madshus RACE PRO CLASSIC размер 38-48', CAST(13199.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (75, N'pYVbFC0puTXoeA', N'Крепления для беговых лыж Fischer WORLD CUP CLASSIC IFP (Turnamic)', CAST(5499.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (76, N'qj9XhJnwWCdaYv', N'Крепления для беговых лыж Nordway 75 мм', CAST(249.0000 AS Money), 19)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (77, N'sNxfxmuboDsSo8', N'Кроссовки мужские Salomon XA Oribi размер 40-46', CAST(4999.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (78, N'FNDNqty3WbqPFa', N'Кроссовки мужские Nike Juniper Trail размер 40-46', CAST(6299.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (79, N'f1WgaB1ykKA5zX', N'Спортивный топ бра ASICS Logo размер 40-50 цвет розовый ', CAST(2499.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (80, N'MQtnhLm1XUl6SX', N'Спортивное бра Odlo Zaha размер 42-44 цвет черный', CAST(4999.0000 AS Money), 12)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (81, N'npIfbxz3MokcT3', N'Зажим для носа Speedo', CAST(699.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (82, N'wU9LZdEOYgbNfP', N'Беруши Joss', CAST(204.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (83, N'QUKL4EikYjQFaY', N'Лопатки для гребли Joss', CAST(699.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (84, N'DDiUOS5z4xZWEq', N'Доска для плавания Joss', CAST(899.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (85, N'HVUVDu9BvlnWmC', N'Колобашка Joss', CAST(899.0000 AS Money), 26)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (86, N'VlZ0l45oQM3quf', N'Лопатки для гребли Speedo Finger', CAST(1799.0000 AS Money), 24)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (87, N'VFE67lU72gELxp', N'Ласты Speedo Training Fin размер 34-47', CAST(4399.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (88, N'nVbHBRzzkPyDnE', N'Доска для плавания Speedo', CAST(1999.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (89, N'PLl0lq7dTdDkKq', N'Беруши Speedo Biofuse Aquatic Earplug', CAST(699.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (90, N'k9fJVd6slgWVIz', N'Лопатки для гребли Speedo Fastskin', CAST(3599.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (91, N'rzbWei1uus30vX', N'Гидрокостюм мужской Termit размер 50-54, цвет черный ', CAST(7999.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (92, N'Ce3SHS5AVQAwt2', N'Гидрокостюм неопреновый короткий женский Joss, 1,5 мм размер 40-46', CAST(2699.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (93, N'iBbFgNztVeWMjC', N'Гидрокостюм неопреновый женский Joss, 3 мм размер 40-46', CAST(5599.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (94, N'4u56eR4MFzqLW1', N'Гидрокостюм неопреновый короткий мужской Joss, 1,5 мм размер 48-54 цвет черный', CAST(5599.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (95, N'XTIl6CosVzAh0v', N'Гидрокостюм неопреновый мужской Joss, 3 мм размер 42-54', CAST(5599.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (96, N'5krNUnG5DoRuJN', N'Гидрокостюм неопреновый мужской с капюшоном Joss, 5 мм размер 48-54', CAST(7199.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (97, N'0iORfPAf4v9MWA', N'Гидрокостюм неопреновый короткий мужской Joss, 2,5 мм размер 48-54', CAST(3399.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (98, N'ZEpdP1dukUnAvr', N'Шорты неопреновые мужские Joss, 2 мм размер 44-54 ', CAST(1999.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (99, N'D3AVfRZhVdafj7', N'Куртка для сплава женская Hiko NIMUE Cag размер 48-54', CAST(15399.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (100, N'1m7vewcLQ6iYSf', N'Брюки для сплава Hiko SNAPPY 18 размер 48-54', CAST(16499.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (101, N'qOWP3QIZ3vuy8u', N'Купальник женский Joss размер 42-50 цвет черный', CAST(499.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (102, N'pNkD87FB2jubGg', N'Купальник женский Joss размер 42-52 цвет черный, фиолетовый', CAST(399.0000 AS Money), 14)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (103, N'gyngOk1my86gXJ', N'Лиф женский Termit размер 40-50 с принтом черный', CAST(899.0000 AS Money), 13)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (104, N'K9kL4k7HG8QWOz', N'Купальник женский Joss размер 42-54 черный с кружевом', CAST(1999.0000 AS Money), 20)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (105, N'mPSyyY2ADuYTnw', N'Купальник женский FILA размер 42-52 синий', CAST(899.0000 AS Money), 12)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (106, N'9Nv19TaR1eSATg', N'Лиф женский Protest Superbird размер 42-40 цвет белый черный', CAST(2099.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (107, N'6bN6yG3pd0dpE7', N'Плавки женские Joss размер 42-52 цвет бордо', CAST(399.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (108, N'7RkOnlBkHjvPJQ', N'Шорты мужские Speedo Fitted размер 46-56 цвет голубой', CAST(1199.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (109, N'XFlLCS6iZJIgOL', N'Шорты плавательные мужские FILA размер 46-56 цвет серый синий', CAST(1599.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (110, N'DaMkB7qcTuGvip', N'Шорты плавательные мужские Joss размер 46-58 цвет синий', CAST(979.0000 AS Money), 12)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (111, N'6j8HwMbgz639cw', N'Очки для плавания Speedo красные', CAST(2799.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (112, N'6Z8etDnB1afGGr', N'Очки для плавания Speedo Fut Biof синие', CAST(2199.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (113, N'fWM1fLYgKZavWy', N'Очки для плавания Speedo черные', CAST(2399.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (114, N'SyiWph0iiCbBXV', N'Очки для плавания Joss белые', CAST(599.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (115, N'KoERse1tazcjSL', N'Очки для плавания FILA синие', CAST(1299.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (116, N'jIU6c0ffZZ3vaQ', N'Очки для плавания детские Speedo Jet V2 оранжевый синий', CAST(899.0000 AS Money), 12)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (117, N'WVFkehr4G2cXaX', N'Очки для плавания детские Joss розовый', CAST(899.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (118, N'WO8gCxLx26PPVV', N'Очки для плавания детские Speedo Biofuse Rift синий желтый', CAST(1999.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (119, N'W8yyoSZcdv8Kn9', N'Очки для плавания детские Speedo Futura Biofuse Flexiseal Mirror Junior зеленый фиолетовый ', CAST(2499.0000 AS Money), 3)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (120, N'P4jNZwb06dooN7', N'Очки для плавания Joss желтый черный', CAST(1299.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (121, N'rS1i1epNAI1REZ', N'Коньки хоккейные детские Bauer VAPOR X2.9, 2020-21 размер 36-38', CAST(24990.0000 AS Money), 1)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (122, N'Xy2bPqmDv9pE49', N'Коньки хоккейные детские Nordway NDW350 JR размер 24-36', CAST(3199.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (123, N'UnhWj67RD9WGBR', N'Коньки хоккейные Nordway NDW 700 SR, 2020-21 размер 39-46', CAST(7659.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (124, N'dAw86kl1MRtuWg', N'Коньки хоккейные Bauer VAPOR X2.9, 2020-21 размер 39-47', CAST(32999.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (125, N'2sYTWEmB50Vz3G', N'Клюшка хоккейная детская Bauer VAPOR X2.7 GRIP', CAST(7699.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (126, N'4GKgYbRHJlbLbp', N'Клюшка хоккейная Fischer CT150 CLEAR SR', CAST(3300.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (127, N'XGPGgV4OQ7KhJj', N'Клюшка хоккейная детская Bauer S18 NEXUS N 2700', CAST(8200.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (128, N'q4e8v0MYDgUVqO', N'Шайба хоккейная', CAST(150.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (129, N'Rvy1zcUIV4iobs', N'Шайба хоккейная детская', CAST(120.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (130, N'pcAej69F4dgwQ0', N'Клюшка хоккейная Bauer SUPREME 3S PRO GRIP', CAST(19999.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (131, N'4tKO0Brfj33Q1W', N'Коньки фигурные Graf ACE SPECIAL, 2020-21 размер 25-35', CAST(12749.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (132, N'0LYBm6YJIYz3Dt', N'Коньки фигурные женские Nordway BELLA, 2020-21 размер 36-42 ', CAST(2499.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (133, N'FFWHKCQv2UEAd4', N'Коньки фигурные Nordway Laval, 2020-21 размер 36-44 черные', CAST(3999.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (134, N'IAIySUP8ulW4Ma', N'Сноуборд Salomon Sight', CAST(23190.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (135, N'cOh2wLNEHjWKgd', N'Сноуборд детский Burton After school SPE', CAST(19039.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (136, N'GWrnsS4yWxGUor', N'Сноуборд женский Termit Aura', CAST(11999.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (137, N'2gBBkvoWU5hJCj', N'Сноуборд Termit Illusion', CAST(15999.0000 AS Money), 3)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (138, N's28I57li7G2rtm', N'Сноуборд женский CAPITA SPACE METAL FANTASY', CAST(27999.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (139, N'wYub8L19toetdQ', N'Сноуборд детский Termit Hero', CAST(6969.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (140, N'ZMfOxUZt2KoXQW', N'Сноуборд CAPITA HORRORSCOPE', CAST(27999.0000 AS Money), 5)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (141, N'FVoPmqvAdC4PzF', N'Горные лыжи Volkl Bash 81 размер 168-178', CAST(24999.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (142, N'tyiAuf3TX3zWVr', N'Горные лыжи Volkl Rise Above 88 размер 163-177', CAST(32999.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (143, N'CLxJc7hJLZ0hcX', N'Горные лыжи + крепления BLIZZARD FIREBIRD SRC размер 175', CAST(69999.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (144, N'5VqFerQXuU7f24', N'Горные лыжи + крепления Salomon S/MAX 12 + Z12 GW размер 175', CAST(57999.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (145, N'LyrPsM3DpioVeE', N'Ботинки горнолыжные Atomic HAWX PRIME 130 S', CAST(35999.0000 AS Money), 2)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (146, N'KyOrQomC4U8f4g', N'Ботинки горнолыжные Tecnica MACH SPORT HV 70', CAST(14399.0000 AS Money), 4)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (147, N'N3FXYmXiX2Ff34', N'Ботинки горнолыжные Tecnica MACH SPORT HV 100', CAST(23399.0000 AS Money), 8)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (148, N'hauxZGXN23DnYu', N'Шлем Termit Basis черный', CAST(2199.0000 AS Money), 7)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (149, N'1FDciTGZpTltco', N'Шлем Uvex hlmt 600 visor черный', CAST(25999.0000 AS Money), 6)
INSERT INTO [dbo].[Sport] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (150, N'XaGbtlkxxrKftq', N'Шлем Salomon DRIVER Dr. черный', CAST(16990.0000 AS Money), 2)
SET IDENTITY_INSERT [dbo].[Sport] OFF
