SET IDENTITY_INSERT [dbo].[Cosmetics] ON
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (11, N'h8cPCFV21uHZPe', N'Карандаш для бровей Stellary коричневый', CAST(399.0000 AS Money), 13)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (12, N'zBfgnNraoVJInR', N'Enough Тональный крем Collagen Moisture Foundation SPF 15, 100 мл', CAST(329.0000 AS Money), 9)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (13, N'AAnwovKEn3kNqg', N'Pupa Luminys пудра компактная запеченная Silky Baked Face Powder', CAST(749.0000 AS Money), 12)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (14, N'Vj4XZXOVyringc', N'Poetea Набор для контуринга Contour Duet', CAST(672.0000 AS Money), 13)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (15, N'mh093i7X1MkdAg', N'Poetea Консилер Party Cover Stick', CAST(635.0000 AS Money), 11)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (16, N'pueBGc1u9sehhd', N'MAKEOVER Румяна Single Blush', CAST(341.0000 AS Money), 19)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (17, N'W3m8S5zyxD2XVd', N'GARNIER BB крем-ролик для кожи вокруг глаз Секрет совершенства, 7 мл', CAST(322.0000 AS Money), 9)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (18, N'j0H1fQVBfJXzbz', N'BE I Масло-праймер Primer Make Up Face Oil 30 мл', CAST(290.0000 AS Money), 5)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (19, N'sAVbiRURXU9K3e', N'Lancome Тональный крем Skin Feels Good, 32 мл', CAST(1199.0000 AS Money), 12)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (20, N'07dW45vRA8XMhf', N'Maybelline New York Face Studio Хайлайтер Shimmer Highlight', CAST(342.0000 AS Money), 14)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (21, N'vFi39pIR1W9NNx', N'Профессиональный маникюрно-педикюрный набор Planta PL-MAN10, 7 насадок, 5 скоростей, подсветка', CAST(1990.0000 AS Money), 2)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (22, N'X9XoOapttV5prt', N'Гель-лак для ногтей ADRICOCO Gel Polish, 8 мл, 056 светло-бежевый', CAST(141.0000 AS Money), 20)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (23, N'RUg1o4FBTJAvWY', N'Гель-лак для ногтей Runail Professional Liker, 9 мл, 4520', CAST(120.0000 AS Money), 14)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (24, N'7brEXMqZh0vWag', N'Гель-лак для ногтей Arbix Classic, 10 мл, 064 Симфония любви', CAST(135.0000 AS Money), 16)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (25, N'Az4ZOCe47hrJGY', N'Nano Professional базовое покрытие NANLAC Gum 15 мл прозрачный', CAST(808.0000 AS Money), 13)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (26, N't0761g3ZqPm8Lq', N'Essie базовое покрытие All In One Base 13.5 мл прозрачный', CAST(399.0000 AS Money), 6)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (27, N'CKGLhSjSrjcVQG', N'IQ BEAUTY базовое покрытие Rubber Base Coat + Ca камуфлирующее 10 мл сливочный пломбир', CAST(421.0000 AS Money), 17)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (28, N'62CmggFaHRAaAw', N'Лак Essie Nail Lacquer, 13.5 мл, 48 изысканный смокинг', CAST(283.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (29, N'vKqPP2uIOwDXMe', N'Слайдер-дизайн для ногтей', CAST(56.0000 AS Money), 14)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (30, N'oD7mvu3zSbPJoV', N'Палочки апельсиновые для маникюра / маникюрные палочки 100шт', CAST(280.0000 AS Money), 16)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (31, N'RI8MXTyUq5xraf', N'Молочко для автозагара GARNIER Ambre Solaire для лица и тела Ровный загар 150 мл', CAST(503.0000 AS Money), 6)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (32, N'zwrP9N6WsEGbaE', N'Гель для тела Holika Holika Aloe 99% Soothing Gel универсальный несмываемый, 55 мл', CAST(270.0000 AS Money), 12)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (33, N'JKBc8fRxrEYjW3', N'GARNIER Ambre Solaire молочко после загара с алоэ вера 200 мл', CAST(405.0000 AS Money), 17)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (34, N'posgZoNIrCRn2M', N'Dove антиперспирант, спрей, Nourishing Secrets Ритуал красоты Пробуждение, 150 мл', CAST(110.0000 AS Money), 22)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (35, N'NJQbXIMPO7Qk0V', N'Гель-крем для душа Palmolive Натурэль Интенсивное увлажнение, 250 мл', CAST(125.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (36, N'2bCgELuafDXOGE', N'Крем-гель для душа Nivea Абрикос, 250 мл', CAST(110.0000 AS Money), 16)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (37, N'SXjWwILtQYsNno', N'Гель для душа 3 в 1 Fa Men Энергия Полинезии Свежесть грозы, 250 мл', CAST(87.0000 AS Money), 18)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (38, N'QnI89hqaiq8hIs', N'ItalWax Пленочный воск Full Body wax в гранулах 1000 г', CAST(1299.0000 AS Money), 13)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (39, N'2ioJ48t4FWP3em', N'Крем-мыло кусковое Dove Красота и уход, 100 г', CAST(66.0000 AS Money), 19)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (40, N'pJGdoWpjR47CrB', N'Гель для душа Nivea Men Сила угля, 250 мл', CAST(150.0000 AS Money), 22)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (41, N'f7baRzd64PDyKu', N'Sim Sensitive System 4 Биоботаническая сыворотка Bio Botanical Serum, 100 мл', CAST(970.0000 AS Money), 22)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (42, N'DvTh1uLWQ4ClTg', N'Sim Sensitive System 4 Маска терапевтическая Oil Cure Hair Mask "О", 100 мл', CAST(855.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (43, N'zEblNPRA8Ijsc2', N'Cafe mimi Экспресс-маска для волос для восстановления поврежденных волос ', CAST(125.0000 AS Money), 17)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (44, N'NUSPOplthuFJQU', N'Kapous Professional Профессиональный уход Сыворотка увлажняющая', CAST(389.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (45, N'RUKJH983vudKRA', N'GARNIER Комплексный несмываемый уход Fructis SOS Спасатель волос 10 в 1, 400 мл', CAST(199.0000 AS Money), 14)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (46, N'ryEhU6raJpDiTb', N'Lador Маска для сухих и поврежденных волос Hydro LPP Treatment, 530 мл', CAST(743.0000 AS Money), 21)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (47, N'4h11kDWimS65Cq', N'Sim Sensitive System 4 Тоник терапевтический Climbazole Scalp Tonic "T", 100 мл', CAST(545.0000 AS Money), 12)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (48, N'gjKVNzPxFhDs18', N'Constant Delight Эликсир для волос 12 в 1, 200 мл', CAST(480.0000 AS Money), 19)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (49, N'wEAjbrGa4Kxqwj', N'Masil Маска-филлер для волос 8 Seconds Salon Hair Mask, 200 мл', CAST(720.0000 AS Money), 5)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (50, N'l346iEswuHIZ4n', N'GARNIER Маска 3 в 1 для очень сухих волос Fructis SuperFood Банан, 390 мл', CAST(276.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (51, N'WheQGAp0AdJfA9', N'Парфюмерная вода Lancome Idole, 25 мл', CAST(4425.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (52, N'VRz2ZEQM2oRfVQ', N'Парфюмерная вода Lanvin Eclat dArpege pour Femme, 30 мл', CAST(2299.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (53, N'0vm1brkSN92fIO', N'Парфюмерная вода Lancome Poeme, 30 мл', CAST(3640.0000 AS Money), 15)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (54, N'5SChE1Q88azjai', N'Туалетная вода Christian Dior Fahrenheit, 200 мл', CAST(13914.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (55, N'XRdICO8tfJVr9e', N'Парфюмерная вода GIVENCHY LInterdit (2018)', CAST(1920.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (56, N'N1hPbhff0nD64k', N'Туалетная вода DOLCE & GABBANA 3 LImperatrice, 100 мл', CAST(4200.0000 AS Money), 30)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (57, N'JGatvtxcgpahfK', N'Туалетная вода Antonio Banderas The Icon, 50 мл', CAST(1190.0000 AS Money), 14)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (58, N'rJCB5NB8qh15NM', N'Парфюмерная вода LACOSTE Lacoste pour Femme, 30 мл', CAST(2772.0000 AS Money), 10)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (59, N'MVRZ9Qjq7Z3Dqq', N'Парфюмерная вода Lancome La Vie est Belle, 4 мл', CAST(1550.0000 AS Money), 16)
INSERT INTO [dbo].[Cosmetics] ([Id], [Артикул], [Модель], [Цена], [Количетво]) VALUES (61, N'PzRDskIPsNIqAO', N'Туалетная вода Escentric Molecules Escentric 02, 100 мл', CAST(8550.0000 AS Money), 18)
SET IDENTITY_INSERT [dbo].[Cosmetics] OFF
