SET IDENTITY_INSERT [dbo].[Electronics] ON
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (11, N'agXYHA2f7dxDVa', N'Наушники TWS Apple AirPods Pro белый', CAST(18999.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (12, N'YNPwXYQbAR9vMo', N'Наушники TWS Apple Airpods (MV7N2RU/A) белый', CAST(11999.0000 AS Money), 4)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (13, N'zMiki0stY7kKml', N'Наушники TWS Samsung Galaxy Buds+ черный', CAST(8499.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (14, N'4arERu88u2zIMt', N'Наушники TWS Xiaomi Mi True Wireless Earbuds Basic 2 черный', CAST(1599.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (15, N'ERKduvtrHPgSoJ', N'Проводная гарнитура Logitech G PRO X черный', CAST(8199.0000 AS Money), 3)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (16, N'2ZhZcnXbpUvqdI', N'Наушники TWS Apple Airpods (MRXJ2RU/A) белый', CAST(14999.0000 AS Money), 2)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (17, N'PZareJd9onNrCd', N'Проводная гарнитура HyperX Cloud Core 7.1 HX-HSCC-2-BK черный', CAST(7499.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (18, N'ypmUAykH8OdFzJ', N'Наушники TWS Realme Buds Air Neo белый', CAST(3499.0000 AS Money), 14)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (19, N'v1x9Y2vswBC5oJ', N'Радиочастотные наушники PlayStation PULSE 3D белый', CAST(8999.0000 AS Money), 12)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (20, N'9I3s7kmywqSfkh', N'Наушники TWS Samsung Galaxy Buds Live черный', CAST(10999.0000 AS Money), 3)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (21, N'Gkw31z0s2Acbxz', N'Смартфон Apple iPhone 11 128 ГБ черный', CAST(55199.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (22, N'YtVvlmw4uH1baI', N'Смартфон Xiaomi Redmi 9A 32 ГБ зеленый', CAST(8499.0000 AS Money), 5)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (23, N'jNXIDtd6vBjR2p', N'Смартфон Samsung Galaxy A52 256 ГБ фиолетовый', CAST(31699.0000 AS Money), 4)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (24, N'M3DaIpxXDie6Ze', N'Смартфон Samsung Galaxy S21 128 ГБ серый', CAST(66899.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (25, N'STK0tzNWLUfhEm', N'Смартфон Samsung Galaxy A72 128 ГБ черный', CAST(34500.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (26, N'bMUaSuw3Z5QxZO', N'Смартфон POCO X3 Pro 256 ГБ синий', CAST(24000.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (27, N'2hxJ7tVLAtlOox', N'Смартфон realme C21 64 ГБ черный', CAST(10000.0000 AS Money), 14)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (28, N'85DD1gyyghQDKL', N'Смартфон Samsung Galaxy A51 64 ГБ белый', CAST(17900.0000 AS Money), 15)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (29, N'VZ7cZ5xUDuDxTX', N'Смартфон Samsung Galaxy A51 128 ГБ красный', CAST(20900.0000 AS Money), 13)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (30, N'aK9Cg5jm23h7jw', N'Смартфон Samsung Galaxy Note 20 Ultra 256 ГБ черный', CAST(74990.0000 AS Money), 2)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (31, N'X8Km9oD7uKlrsD', N'Камера со сменной оптикой Canon EOS M50 Kit 15-45mm IS STM черный', CAST(45000.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (32, N'J2CrTSXCaPZgEp', N'Камера со сменной оптикой Sony Alpha ILCE-7M3 Body черный', CAST(149999.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (33, N'gzExqatfwTTgB1', N'Камера со сменной оптикой Nikon Z 5 Body + переходник байонета FTZ черный', CAST(110699.0000 AS Money), 4)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (34, N'jP7vvzNmsX7bAN', N'Камера со сменной оптикой Sony Alpha ILCE-7M3K Kit 28-70mm черный', CAST(164999.0000 AS Money), 2)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (35, N'di5MQOZAVWbUFH', N'Камера со сменной оптикой Canon EOS R6 kit RF 24-105 F4-7.1 IS STM черный', CAST(234999.0000 AS Money), 3)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (36, N'TlTEjFcsKze4dh', N'Камера со сменной оптикой Fujifilm X-A5 Kit 15-45mm серый', CAST(29999.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (37, N'Ng2DiEWvYaGYbB', N'Камера со сменной оптикой Fujifilm X-A5 Kit 24-75mm серый', CAST(31299.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (38, N'bgyQqUwsKgcKwX', N'Камера со сменной оптикой Olympus PEN E-PL9 Pancake Kit 14-42mm EZ белый', CAST(39999.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (39, N'WRfAc37SHc07wx', N'Камера со сменной оптикой Panasonic Lumix DMC-GX80 черный', CAST(42299.0000 AS Money), 5)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (40, N'DjdlOqFakDKVk9', N'Камера со сменной оптикой Panasonic Lumix DC-GX880 kit 12-32mm серебристый', CAST(44999.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (41, N'n1YDRKsy51p7Ew', N'Ноутбук Lenovo IdeaPad 3 15ARE05 серый', CAST(40999.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (42, N'tDzbntFU7JTNtW', N'Ноутбук Apple MacBook Air серый', CAST(101999.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (43, N'qUe6WlVn0klCde', N'Ноутбук Acer Nitro 5 AN515-45-R4SB черный', CAST(91999.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (44, N'RTt9ob8hfQlzcU', N'Ноутбук Lenovo IdeaPad 3 Gaming 15ARH05 черный', CAST(52199.0000 AS Money), 4)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (45, N'jSStMy60uwWmYX', N'Ноутбук MSI GF75 10UEK-047RU черный', CAST(134999.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (46, N'Ol7r6QKmZm6QXZ', N'Ноутбук Lenovo IdeaPad 5 14ARE05 серый', CAST(46999.0000 AS Money), 12)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (47, N'fECMWODXlL2W2J', N'Ноутбук Honor MagicBook Pro HLYL-WFQ9 серый', CAST(68999.0000 AS Money), 10)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (48, N'fqQsTT3ujDETBj', N'Ноутбук ASUS Laptop D509DA-BQ053 серебристый', CAST(43999.0000 AS Money), 21)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (49, N'TLUdWkTDmuPozN', N'Ноутбук Acer TravelMate B1 TMB118-M-C0EA черный', CAST(13899.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (50, N'QVxs9fd3sME87A', N'Ноутбук ASUS TUF Gaming FX706LI-H7057T черный', CAST(74699.0000 AS Money), 13)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (51, N'bHNueqxXYEDTrU', N'Телевизор LED Xiaomi Mi TV 4S 43 серебристый', CAST(27999.0000 AS Money), 1)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (52, N'dLb6SiPX2yUWNF', N'Телевизор LED Xiaomi Mi TV 4S 65 черный', CAST(59999.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (53, N'syHrWacV4KP7Ph', N'Телевизор LED Xiaomi Mi TV 4A 55 черный', CAST(32999.0000 AS Money), 3)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (54, N'VllJJajRLyOKOt', N'Телевизор LED Xiaomi Mi TV 4A 43 черный', CAST(26999.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (55, N'MV74UFCDrAWovz', N'Телевизор LED DEXP H32F7000K черный', CAST(9499.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (56, N'p0NlRX2rnBL4y7', N'Телевизор LED Samsung UE43TU7002UXRU черный', CAST(30499.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (57, N'G2sutY1UCz1Pmn', N'Телевизор LED LG 65UN73506LB серый', CAST(59999.0000 AS Money), 4)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (58, N'zQEGzhFCB4Te9Z', N'Телевизор LED LG 55NANO866NA черный', CAST(54999.0000 AS Money), 2)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (59, N'XcLNhpxPLMmTXj', N'Телевизор LED Samsung UE50TU8500UXRU черный', CAST(52999.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (60, N'UW1aAFnogWe1nq', N'Телевизор LED DEXP H32F8000Q черный', CAST(12499.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (61, N'yYakhSdyWv3C1C', N'Коннектор RJ45 Lanmaster TWT-PL45-8P8C', CAST(599.0000 AS Money), 12)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (62, N'LKxriuPYY7dIGB', N'Проходной соединительный адаптер RJ45 FinePower RJ45 кат. 5e (8P8C)', CAST(99.0000 AS Money), 16)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (63, N'iBhjzIkA2XP2Fl', N'Настенная розетка RJ45 FinePower RJ45', CAST(320.0000 AS Money), 19)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (64, N'3bElDg3GSR1wAb', N'Проходной соединительный адаптер RJ45 Ugreen 20390', CAST(299.0000 AS Money), 14)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (65, N'4gWSj1UxrdtxHA', N'Коннектор RJ45 Rexant 06-0082-A10', CAST(160.0000 AS Money), 13)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (66, N'UvqiBNoE1MEDqi', N'Коннектор RJ45 Ugreen 20333', CAST(160.0000 AS Money), 17)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (67, N'mHuEpxZI2ykFTs', N'Модуль Keystone Hyperline KJNE-8P8C-C5e-90-GN', CAST(150.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (68, N'aSocOZl3MdpXoB', N'Изолирующий защитный колпачок RJ45 FinePower RJ45', CAST(49.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (69, N'Pky41WgCTnSQot', N'Модуль Keystone Hyperline KJNE-8P8C-C6-90-SH-F-WH', CAST(370.0000 AS Money), 9)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (70, N'WYn7anDSfEC2wR', N'Модуль Keystone Lanmaster TWT-OK45STP/5E-WH', CAST(220.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (71, N'1GRkqIsa2PadF1', N'Центр управления умным домом Sibling Powernet-ZGW', CAST(1999.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (72, N'8Up2zE6wjubtnm', N'Беспроводной выключатель Yeelight Smart Switch Light YLKG12YL белый', CAST(499.0000 AS Money), 8)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (73, N'kzc1heA6CrKHh7', N'Датчик открытия Ginzzu HS-S03W', CAST(499.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (74, N'lxlEtdx6J9Ddf4', N'Датчик утечки газа GiNZZU HS-S39W2', CAST(999.0000 AS Money), 5)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (75, N'VgQMw8zJs0EY8z', N'Брелок-актуатор Viguard KEYFOB F', CAST(1199.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (76, N'PZtQ1Vf9iIxeZ7', N'Датчик протечки воды First Alert WA100', CAST(1199.0000 AS Money), 4)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (77, N'h94yLq8leOsnq1', N'Пульт управления Ajax SpaceControl', CAST(1350.0000 AS Money), 7)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (78, N'lRJgK9URacpVVx', N'Датчик дыма First Alert PR700', CAST(1699.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (79, N'NeVVw0MpKZzgfh', N'Модуль интеграции Ajax Transmitter', CAST(2250.0000 AS Money), 6)
INSERT INTO [dbo].[Electronics] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (80, N'AqBI6JvlQvPbg9', N'Управляемое реле Ajax Relayslide 1 to 4 of 4', CAST(2250.0000 AS Money), 3)
SET IDENTITY_INSERT [dbo].[Electronics] OFF
