SET IDENTITY_INSERT [dbo].[Users] ON
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (1, N'ashxwi@gmail.com', N'aWQasf38b2f', N'Василиса', N'Мухина', N'79796964691', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (2, N'anjela.kudasheva@gmail.com', N'd0f038b2f', N'Ольга', N'Кочетова', N'79834264234', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (3, N'marfa9836@gmail.com', N'0c09297f6', N'Елизавета', N'Козлова', N'79478383799', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (4, N'valeriy1985@gmail.com', N'201711106', N'Амелия', N'Позднякова', N'79782114134', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (5, N'yaroslava33@gmail.com', N'3865ff2d9', N'Кирилл', N'Сидоров', N'79132784271', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (6, N'sevastyan9586@gmail.com', N'caeb695bc', N'Михаил', N'Шилов', N'79719255460', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (7, N'rostislav86@gmail.com', N'64635eb56', N'Алиса', N'Орлов', N'79978037893', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (8, N'petr25081963@gmail.com', N'e51f29274', N'Кирилл', N'Попов', N'79209271820', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (9, N'afanasiy.kizyurin@gmail.com', N'6eeebb57e', N'Пётр', N'Наумов', N'79242433932', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (10, N'elena2755@gmail.com', N'02a7fd0bc', N'Мирослава', N'Игнатова', N'79706383587', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (11, N'fdd@yandex.ru', N'6eeebdab57e', N'Яна', N'Дмитриева', N'79708473587', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (12, N'SD@SDD.COM', N'qsqebb57e', N'Амина', N'Алехина', N'79706368087', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (45, N'frinco@yandex.ru', N'1234', N'Александр', N'Нисман', N'79706368087', N'admin')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (48, N'fsnisman@gmail.com', N'1234', N'Alex', N'Nisman', N'76049272985', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (49, N'ysd@gmail.com', N'5555', N'Макс', N'Пионер', N'79655847691', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (50, N'evgenuss@gmail.ru', N'Sonic1312', N'Евгений', N'Лупарь', N'76049268157', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (51, N'ascijiaoo@gamil.com', N'123456789xsdfasd', N'Максим', N'Петухов', N'79571812674', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (52, N'tisckks@gmail.com', N'123456', N'Алекснадр', N'Гаралов', N'79607482495', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (53, N'georgi@yandex.ru', N'1234', N'Георгий', N'Фардей', N'79844957592', N'user')
INSERT INTO [dbo].[Users] ([Id], [Login], [Password], [Имя], [Фамилия], [Телефон], [Статус]) VALUES (54, N'kvasnikova78@mail.ru', N'159753', N'Марина', N'Квасникова', N'89649168802', N'user')
SET IDENTITY_INSERT [dbo].[Users] OFF
