SET IDENTITY_INSERT [dbo].[Appliances] ON
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (11, N'dsqoqEab2mOgDs', N'Масляный радиатор Ballu Classic BOH/CL-07WRN белый', CAST(3050.0000 AS Money), 6)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (12, N'ML6cyedvxtfTx0', N'Масляный радиатор Hyundai H-HO-9-07-UI847 белый', CAST(2599.0000 AS Money), 4)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (13, N'UzQiurPZIbjOxz', N'Масляный радиатор Hyundai H-HO-9-09-UI848 белый', CAST(3150.0000 AS Money), 7)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (14, N'NcTLxHmxBbDb6i', N'Масляный радиатор Ballu Turbo BOH/TB- 07FH белый', CAST(4650.0000 AS Money), 5)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (15, N'ZIyXWvB0wsnAWm', N'Масляный радиатор Electrolux Line EOH/M - 7157 белый', CAST(3899.0000 AS Money), 4)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (16, N'SDG1KushDi1ORu', N'Масляный радиатор Ballu Great BOH/GT-11W 2200 белый', CAST(4350.0000 AS Money), 7)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (17, N'kf3TmAwgaNSzOs', N'Масляный радиатор Aceline OL-2009B черный', CAST(2750.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (18, N'JJZvqOLfe0wWpo', N'Масляный радиатор Zanussi LOFT ZOH/LT-07W белый', CAST(4299.0000 AS Money), 14)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (19, N'ASWCA45XfmkeA7', N'Масляный радиатор Ballu Classic BOH/CL-09WRN белый', CAST(3650.0000 AS Money), 12)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (20, N'BDORD9PSFYEBis', N'Масляный радиатор Electrolux Sport Line EOH/M-5221N белый', CAST(5299.0000 AS Money), 13)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (21, N'xDmuU3C1cy3tZI', N'Холодильник с морозильником LG GA-B459CQWL белый', CAST(33999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (22, N'VCRhTE0I4Kbecx', N'Холодильник с морозильником INDESIT DSN 18 белый', CAST(19999.0000 AS Money), 12)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (23, N'oPB3M0SJxGBgxX', N'Холодильник с морозильником BEKO RCNK310KC0W белый', CAST(30499.0000 AS Money), 6)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (24, N'c3D0P18E1NMDKk', N'Холодильник с морозильником INDESIT DFN 18 D белый', CAST(26999.0000 AS Money), 7)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (25, N'8q1IcX9ZC9iKV5', N'Холодильник с морозильником DEXP TF275D белый', CAST(16999.0000 AS Money), 5)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (26, N'ldlGqdvX68VLNn', N'Холодильник с морозильником LG GA-B459CLWL серебристый', CAST(33999.0000 AS Money), 5)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (27, N'RwLfpDzwFe5JTt', N'Холодильник компактный DEXP RF-SD090MA/W белый', CAST(10499.0000 AS Money), 7)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (28, N'L4i9dKcAusUnXp', N'Холодильник с морозильником BEKO CNKDN6335KC0W белый', CAST(22999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (29, N'Z2mPCZBGCHkJGV', N'Холодильник с морозильником Indesit ITR 5200 X серебристый', CAST(29999.0000 AS Money), 13)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (30, N'tmiwR1sEg6y3WE', N'Холодильник с морозильником LG GA-B509CAZL серебристый', CAST(35999.0000 AS Money), 15)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (31, N'OnlfoCf3VZXDf3', N'Стиральная машина LG F1296NDS1slide 1 to 9 of 12', CAST(23999.0000 AS Money), 4)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (32, N'vhhT0xRJb5Ut8A', N'Стиральная машина Indesit IWUD 4085 (CIS)', CAST(14999.0000 AS Money), 7)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (33, N'VARSX7EN3YOp8m', N'Стиральная машина LG FH0B8LD6', CAST(22999.0000 AS Money), 9)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (34, N'VK7itxQtzQheoK', N'Стиральная машина LG F12B8WDS7', CAST(24999.0000 AS Money), 8)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (35, N'WFLCRYLayTCrbR', N'Стиральная машина Indesit BWSA 61051 Sslide 1 to 9 of 10', CAST(14999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (36, N'KB8Lkljv5nKOng', N'Стиральная машина LG F1296HDS3', CAST(26999.0000 AS Money), 14)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (37, N'NeQQNYP9giKTDb', N'Стиральная машина LG F2M5HS6S', CAST(25999.0000 AS Money), 19)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (38, N'3q0jWMIf7aPX6N', N'Стиральная машина Candy Smart CSS34 1062D1-07', CAST(13599.0000 AS Money), 15)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (39, N's1HOpdMWedN6s1', N'Стиральная машина Samsung WW65K42E08WDLP', CAST(28899.0000 AS Money), 3)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (40, N'8HaxlcGTgIlDYV', N'Стирально-сушильная машина LG F2V5NG0W', CAST(31999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (41, N'4821ssusj25Tbl', N'Блендер Redmond RHB-2981 черный', CAST(2499.0000 AS Money), 6)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (42, N'CSPcI8bnYCu2ym', N'Блендер Polaris PHB 1397 черный', CAST(2599.0000 AS Money), 6)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (43, N'7FQQPWylR9Clqg', N'Блендер Scarlett SC-HB42F60 белый', CAST(999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (44, N'CmkMQtlnXJLxEO', N'Блендер Philips HR2642/00 белый', CAST(5399.0000 AS Money), 4)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (45, N'MaDwtmHX8BOvB3', N'Блендер Bosch MS6CA4150 белый', CAST(3999.0000 AS Money), 12)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (46, N'uz6FoXSgpGaqRO', N'Блендер Bosch MSM2650B черный', CAST(2899.0000 AS Money), 4)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (47, N'gIRv5aQKSnxwV0', N'Блендер Bosch MS8CM6190 серебристый', CAST(9999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (48, N'0rMplSIhq2XiZ7', N'Блендер Scarlett SC-HB42F56 черный', CAST(1699.0000 AS Money), 15)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (49, N'UV6dhk5EL1wWna', N'Блендер Moulinex DD641132 белый', CAST(2199.0000 AS Money), 5)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (50, N'h6Xo752WebEgW0', N'Блендер Scarlett SC-HB42M33 белый', CAST(1899.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (51, N'FlRbTJRCGMqWFj', N'Кофемашина Philips EP2035/40 черный', CAST(42999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (52, N'G5SqXkzCMHMMyg', N'Кофемашина Delonghi ECAM 250.23.SB серебристый', CAST(30399.0000 AS Money), 5)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (53, N'krQ3lSbFS6RHUd', N'Кофемашина Philips EP3243/70 Wt белый', CAST(40299.0000 AS Money), 4)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (54, N'zDLrphwOsd41v3', N'Кофемашина Nivona CafeRomatica NICR 779 белый', CAST(49999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (55, N'7eyhtNSqNdgAir', N'Кофемашина Nivona NICR 841 черный', CAST(65799.0000 AS Money), 14)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (56, N'KZEM2eyXQcBwcv', N'Кофемашина Delonghi ECAM 22.114.B черный', CAST(24999.0000 AS Money), 10)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (57, N'vb3zvlaf3UOoC0', N'Кофемашина Melitta F 530-102 черный', CAST(41699.0000 AS Money), 15)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (58, N'i00XrrVBBmHN0T', N'Кофемашина Gaggia Naviglio Deluxe Silver серебристый', CAST(56899.0000 AS Money), 14)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (59, N'D7LZkMGGMHkhS8', N'Кофемашина Jura ENA 8 красный', CAST(91099.0000 AS Money), 2)
INSERT INTO [dbo].[Appliances] ([Id], [Артикул], [Модель], [Цена], [Количество]) VALUES (60, N'VCIsGEDiDJuf7R', N'Кофемашина Krups EA829E10 серебристый', CAST(62999.0000 AS Money), 13)
SET IDENTITY_INSERT [dbo].[Appliances] OFF
